# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:              Era Of Chaos
subtitle:           Mobile game wiki
description:        
keywords:           EraOfChaos HMM HeroesMightAndMagic
language:           "en" 
baseurl:            ""   
# the base hostname & protocol for your site. Look at robots.txt as well!
url:                "http://eraofchaos.github.io"
google_ad_client:   "ca-pub-3093097053913638"

theme: jekyll-theme-slate
gems:
  - jekyll-sitemap
  - jekyll-seo-tag
