name: Update all Github pages

on:
  schedule:
    - cron: "23 11 * * *"
#    - cron: "23 */7 * * *"

jobs:
  github-pages:
    runs-on: ubuntu-latest
    name: Update Github Pages Initiatives
    steps:
    - name: Jekyll update github pages without new commit
      uses: DP6/jekyll-update-pages-action@v1.0.1
      with:
        DEPLOY_TOKEN: ${{ secrets.GH_PAGES_DEPLOY_TOKEN }}
        USER: ${{ secrets.GH_PAGES_USER }}
        FILTER:  'is%3Apublic%20org%3Aeraofchaos'